service: backend

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1 # or your preferred AWS region
  environment:
    MONGO_URI: ${env:MONGO_URI}
    EMAIL_USER: ${env:EMAIL_USER}
    EMAIL_PASS: ${env:EMAIL_PASS}
    S3_BUCKET_NAME: ${env:S3_BUCKET_NAME}
  timeout: 30 # Increase timeout to 30 seconds

functions:
  processForm:
    handler: handler.processForm
    events:
      - http:
          path: form
          method: post
          cors:
            origin: '*' # Or specify your frontend's domain for more security
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - Access-Control-Allow-Origin
              - Access-Control-Allow-Headers
            allowCredentials: false # Set to true if you're dealing with cookies

  processPackage:
    handler: handler.processPackage
    events:
      - http:
          path: package
          method: post
          cors:
            origin: '*' # Or specify your frontend's domain for more security
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - Access-Control-Allow-Origin
              - Access-Control-Allow-Headers
            allowCredentials: false # Set to true if you're dealing with cookies

  # storeForm:
  #   handler: handler.storeForm
  #   events:
  #     - http:
  #         path: form/store
  #         method: post
  #         cors: true


plugins:
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  serverless-offline:
    httpPort: 3000
