service: backend

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    MONIME_ACCESS_TOKEN: mon_Ee0sv2kOfGNwtzsB7AzYooaqrewcPr5cJMT8ltYwO1zcH7Qnk1PpxrfoTRm6fhu9

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
          cors: true

  processPayment:
    handler: handler.processPayment
    events:
      - http:
          path: payment
          method: post
          cors: true

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  serverless-offline:
    httpPort: 3000
