service: backend

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1 # or your preferred AWS region
  environment:
    MONGO_URI: ${.env:MONGO_URI}
    EMAIL_USER: ${.env:EMAIL_USER}
    EMAIL_PASS: ${.env:EMAIL_PASS}
    S3_BUCKET_NAME: ${.env:S3_BUCKET_NAME}
  timeout: 30 # Increase timeout to 30 seconds

functions:
  processPayment:
    handler: handler.processPayment
    events:
      - http:
          path: payment
          method: post
          cors: true
  storeForm:
    handler: handler.storeForm
    events:
      - http:
          path: form/store
          method: post
          cors: true

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  serverless-offline:
    httpPort: 3000
